name: Labeler

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    uses: YisusChrist/github-actions-workflows/.github/workflows/labeler.yml@main
    secrets: inherit
